steps:
- template: GenerateCodePR.yml
- bash: |
    logurl="https://$(STORAGE_ACCOUNT).blob.core.windows.net/$(STORAGE_ACCOUNT_CONTAINER)/log/$(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY).log"
    codePR=$(CODE_PULLREQUEST)
    triggerPR="https://github.com/$(CODEGEN_REPO_OWNER)/$(CODEGEN_REPO_NAME)/pull/$(System.PullRequest.PullRequestNumber)"
    sdktarget=$(TARGET)

    org=$(SPEC_REPO_OWNER)
    repo=$(SPEC_REPO_NAME)
    base=$(SPEC_REPO_BASE_BRANCH)

    sdk="";
    to_mail="";
    cc_mail=$(CCEails);
    if [ "$sdktarget" == "terraform" ]; then
      to_mail="tfazengvsc@microsoft.com;sdkautomationpipeline@outlook.com;vsccodegen@microsoft.com"
    fi

    if [ "$sdktarget" == "clicore" ]; then
      to_mail="AzCLIInternal@microsoft.com;sdkautomationpipeline@outlook.com;vsccodegen@microsoft.com"
    fi

    if [ "$sdktarget" == "cliextension" ]; then
      to_mail="AzCLIInternal@microsoft.com;sdkautomationpipeline@outlook.com;vsccodegen@microsoft.com"
    fi

    resolveURL="https://$(CodegenApp_Server)/codegenerations/$(CodeGenerationName)/onboard/customize?triggerPR=$triggerPR&codePR=$codePR"

    python scripts/issueResolve.py "Onboarding" "Please Reolve issues when Onboard '$(ResourceProvider)'" "$logurl" "$codePR" "$triggerPR" "$resolveURL" > scripts/email.html
    # cat scripts/email.html
    to_mail="$(Contactors)"

    sudo pip install wheel
    sudo pip install sendgrid
    python scripts/sendGridemail.py "scripts/email.html" $to_mail "Depth-coverage Issue Resolve" $(API_KEY)

    # update code generation status
  displayName: 'Alert issue'
