steps:
- bash: |
    pwd
    echo "specRetrievalMethod=filesystem" >> .env
    echo "specRetrievalLocalRelativePath=./azure-rest-api-specs/" >> .env
    echo "validationPathsPattern=specification/*/resource-manager/*/**/*.json" >> .env
    npm install @azure-tools/mock-service-host
    cd $(Pipeline.Workspace)/../
    sudo node node_modules/@azure-tools/mock-service-host/dist/src/main.js &

    sleep 3m

    ps -eaf |grep node
    netstat -l
  displayName: 'setup mock server'
